services:

  db-user-primary:
    image: postgres:15-alpine
    container_name: trivia-db-user-primary
    environment:
      POSTGRES_DB: ${DB_USERDB_NAME}
      POSTGRES_USER: ${DB_USERDB_USER}
      POSTGRES_PASSWORD: ${DB_USERDB_PASS}
    ports:
      - "5432:5432"
    volumes:
      # Scripts de inicialização do schema (executados apenas na primeira vez)
      - ./infra/init/userdb:/docker-entrypoint-initdb.d
      - db-user-primary-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERDB_USER} -d ${DB_USERDB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - trivia-net

networks:
  trivia-net:
    driver: bridge

volumes:
  db-user-primary-data:
