grpc:
  port: 9090

spring:
  datasource:
    primary:
      url: jdbc:postgresql://localhost:5434/trivia_users
      username: trivia_users
      password: trivia_pass
    replica:
      url: jdbc:postgresql://localhost:5435/trivia_users
      username: trivia_users
      password: trivia_pass

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: user-service-group

bcrypt:
  strength: ${BCRYPT_STRENGTH:10}

logging:
  level:
    org.springframework.boot.context.properties: DEBUG